### ISSUE TITLE
Feature: Add integration tests

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/datagen#24]
### Is your feature request related to a problem? Please describe.

At the moment we are only testing the schema parsing and the output.

It will be nice to actually test the Kafka producer including both JSON and Avro formats

### Describe the solution you'd like

We can create a docker-compose file with Kafka + CSR and add additional tests to actually run the datagen script out of dry run mode

### Additional context

The tests should run on every PR

**Comment by chuck-alt-delete** [comment]
We can also add a deploy step to build and upload the docker image to docker hub as well. I’m not sure how deploying to npm works

**Comment by bobbyiliev** [comment]
I'll have to look into this on what permissions would be needed for our Docker Hub account!
