### ISSUE TITLE
Feature: end to end tests

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/datagen#59]
### Is your feature request related to a problem? Please describe.

As the code base matures and increases in functionality, we need testing infrastructure to ensure it works properly and does not regress.

### Describe the solution you'd like

I've had great success with test containers for orchestrating external components and end-to-end testing. We can spin up Kafka and schema registries in a test pipeline via docker and then write out records.

**Comment by bobbyiliev** [comment]
Good idea! Actually, I implemented it a couple of days ago already:

https://github.com/MaterializeInc/datagen/blob/main/.github/workflows/integration.yaml

**Comment by sjwiesman** [comment]
Lol. Perfect. I've assigned the issue to you, please open a PR when ready!

**Comment by bobbyiliev** [comment]
Actually it’s already merged here:

https://github.com/MaterializeInc/datagen/pull/36

the integration tests run on every PR

**Comment by chuck-alt-delete** [comment]
Gonna go ahead and close. We can add more integration and unit tests whenever
