### ISSUE TITLE
Feature: Consider migrating to typescript

### ISSUE THREAD

**Issue by sjwiesman** [MaterializeInc/datagen#60]
### Is your feature request related to a problem? Please describe.

I find javascript very difficult to write and maintain. I need types and access modifiers to formulate my thoughts in code. 

### Describe the solution you'd like

I want to open the discussion of migrating to typescript, and I'd like to hear everyone's thoughts for and against it.

**Comment by bobbyiliev** [comment]
I was thinking about this too the other day! Totally agree with you on this one. Will try to work on this!
