### ISSUE TITLE
Feature: Enable client authentication with TLS for Kafka connections

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/datagen#69]
### Is your feature request related to a problem? Please describe.

At the moment we only support SASL and plaintext authentication. We should also support TLS authentication so that users with managed Redpanda Cloud clusters could also use this.

### Additional context

KafkaJS supports this already so it should be trivial to get it implemented:

https://kafka.js.org/docs/configuration#ssl

**Comment by chuck-alt-delete** [comment]
Ah, mutual TLS authentication. I got worried for a second that KafkaJS was sending everything plaintext over the wire.
